# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 00:34


from django.db import migrations, models
import django.db.models.deletion
import materials.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='IDInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100)),
                ('specific_method', models.CharField(max_length=100)),
                ('comments', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('journal', models.CharField(blank=True, max_length=100)),
                ('vol', models.CharField(max_length=100)),
                ('pages_start', models.CharField(max_length=10)),
                ('pages_end', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('doi_isbn', models.CharField(blank=True, max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.Author')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_name', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=30)),
                ('formula', models.CharField(max_length=100)),
                ('organic', models.CharField(max_length=30)),
                ('inorganic', models.CharField(max_length=30)),
                ('last_update', models.DateField()),
                ('description', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AtomicPositions',
            fields=[
                ('idinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='materials.IDInfo')),
                ('fhi_file', models.FileField(blank=True)),
                ('a', models.CharField(max_length=10)),
                ('b', models.CharField(max_length=10)),
                ('c', models.CharField(max_length=10)),
                ('alpha', models.CharField(max_length=10)),
                ('beta', models.CharField(max_length=10)),
                ('gamma', models.CharField(max_length=10)),
                ('volume', models.CharField(blank=True, max_length=10)),
                ('Z', models.CharField(blank=True, max_length=10)),
            ],
            bases=('materials.idinfo',),
        ),
        migrations.CreateModel(
            name='BandGap',
            fields=[
                ('idinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='materials.IDInfo')),
                ('band_gap', models.CharField(max_length=10)),
            ],
            bases=('materials.idinfo',),
        ),
        migrations.CreateModel(
            name='BandStructure',
            fields=[
                ('idinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='materials.IDInfo')),
                ('band_structure', models.CharField(max_length=100)),
            ],
            bases=('materials.idinfo',),
        ),
        migrations.CreateModel(
            name='BondAngle',
            fields=[
                ('idinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='materials.IDInfo')),
                ('hmh_angle', models.CharField(blank=True, max_length=100)),
                ('mhm_angle', models.CharField(blank=True, max_length=100)),
            ],
            bases=('materials.idinfo',),
        ),
        migrations.CreateModel(
            name='BondLength',
            fields=[
                ('idinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='materials.IDInfo')),
                ('hmh_length', models.CharField(blank=True, max_length=100)),
                ('mhm_length', models.CharField(blank=True, max_length=100)),
            ],
            bases=('materials.idinfo',),
        ),
        migrations.CreateModel(
            name='ExcitonEmission',
            fields=[
                ('idinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='materials.IDInfo')),
                ('exciton_emission', models.CharField(max_length=10)),
            ],
            bases=('materials.idinfo',),
        ),
        migrations.AddField(
            model_name='system',
            name='tags',
            field=models.ManyToManyField(blank=True, to='materials.Tag'),
        ),
        migrations.AddField(
            model_name='idinfo',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.UserProfile'),
        ),
        migrations.AddField(
            model_name='idinfo',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.Phase'),
        ),
        migrations.AddField(
            model_name='idinfo',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.Publication'),
        ),
        migrations.AddField(
            model_name='idinfo',
            name='temperature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.Temperature'),
        ),
        migrations.AddField(
            model_name='excitonemission',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.System'),
        ),
        migrations.AddField(
            model_name='bondlength',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.System'),
        ),
        migrations.AddField(
            model_name='bondangle',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.System'),
        ),
        migrations.AddField(
            model_name='bandstructure',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.System'),
        ),
        migrations.AddField(
            model_name='bandgap',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.System'),
        ),
        migrations.AddField(
            model_name='atomicpositions',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.System'),
        ),
    ]
