# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 16:26


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20171226_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idinfo',
            name='temperature',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
    ]
