# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20171031_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='pub_date',
            new_name='pub_year',
        ),
        migrations.RenameField(
            model_name='system',
            old_name='shortname',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='system',
            old_name='aminoacid',
            new_name='tags',
        ),
        migrations.RemoveField(
            model_name='system',
            name='charge',
        ),
        migrations.AlterField(
            model_name='system',
            name='desc',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='system',
            name='inorganic',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='system',
            name='organic',
            field=models.CharField(max_length=30),
        ),
    ]
