# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 18:41


import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20171231_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='last_update',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
