# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20171031_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandGap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_gap', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BandStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_structure', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExcitonEmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exciton_emission', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='excitonemission',
            name='temperature',
            field=models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to='materials.Temperature'),
        ),
        migrations.AddField(
            model_name='bandstructure',
            name='temperature',
            field=models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to='materials.Temperature'),
        ),
        migrations.AddField(
            model_name='bandgap',
            name='temperature',
            field=models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to='materials.Temperature'),
        ),
    ]
