# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_auto_20171101_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='atomicpositions',
            name='code',
            field=models.CharField(default='blah.in', max_length=30),
        ),
        migrations.AlterField(
            model_name='bandgap',
            name='band_gap',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='excitonemission',
            name='exciton_emission',
            field=models.CharField(max_length=10),
        ),
    ]
