# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 15:19


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_auto_20180107_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='institution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='idinfo',
            name='temperature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.Temperature'),
        ),
    ]
