# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 15:23


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_auto_20180108_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idinfo',
            name='temperature',
            field=models.CharField(max_length=20),
        ),
    ]
