# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_auto_20171101_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atomicpositions',
            name='code',
            field=models.CharField(max_length=30),
        ),
    ]
