# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_auto_20171101_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='atomicpositions',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.Phase'),
        ),
        migrations.AddField(
            model_name='atomicpositions',
            name='temperature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.Temperature'),
        ),
        migrations.AddField(
            model_name='bandgap',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.System'),
        ),
        migrations.AddField(
            model_name='bandstructure',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.System'),
        ),
        migrations.AddField(
            model_name='excitonemission',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.System'),
        ),
        migrations.AlterField(
            model_name='atomicpositions',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.System'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='phase',
            field=models.CharField(max_length=20),
        ),
    ]
