# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 17:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_auto_20180108_1523'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temperature',
        ),
        migrations.AlterField(
            model_name='idinfo',
            name='temperature',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
