# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 19:37


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_auto_20180108_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excitonemission',
            name='exciton_emission',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
