# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_auto_20171101_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandgap',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.System'),
        ),
        migrations.AlterField(
            model_name='excitonemission',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.System'),
        ),
        migrations.AlterField(
            model_name='system',
            name='group',
            field=models.CharField(max_length=10),
        ),
    ]
