# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_auto_20171101_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandstructure',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.System'),
        ),
    ]
