# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 17:36


from django.db import migrations, models
import materials.models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_auto_20180119_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='excitonemission',
            name='pl_file',
            field=models.FileField(blank=True),
        ),
    ]
