# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-21 22:24


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_excitonemission_pl_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excitonemission',
            name='exciton_emission',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
