# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-21 22:39


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_auto_20180121_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excitonemission',
            name='pl_file',
        ),
    ]
