# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_auto_20171101_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='atomicpositions',
            name='a',
            field=models.CharField(default=90, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atomicpositions',
            name='alpha',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atomicpositions',
            name='b',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atomicpositions',
            name='beta',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atomicpositions',
            name='c',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atomicpositions',
            name='gamma',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
