# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-21 22:39


from django.db import migrations, models
import materials.models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_remove_excitonemission_pl_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='excitonemission',
            name='pl_file',
            field=models.FileField(blank=True),
        ),
    ]
