# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_auto_20171101_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandgap',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.Author'),
        ),
        migrations.AddField(
            model_name='bandgap',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.Contributor'),
        ),
        migrations.AddField(
            model_name='bandgap',
            name='method',
            field=models.CharField(default='experimental', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bandstructure',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.Author'),
        ),
        migrations.AddField(
            model_name='bandstructure',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.Contributor'),
        ),
        migrations.AddField(
            model_name='bandstructure',
            name='method',
            field=models.CharField(default='experimental', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excitonemission',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.Author'),
        ),
        migrations.AddField(
            model_name='excitonemission',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.Contributor'),
        ),
        migrations.AddField(
            model_name='excitonemission',
            name='method',
            field=models.CharField(default='experimental', max_length=20),
            preserve_default=False,
        ),
    ]
