# Generated by Django 2.0.1 on 2018-01-26 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0013_auto_20180123_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandstructure',
            name='band_structure',
        ),
    ]
