# Generated by Django 2.0.1 on 2018-01-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0014_remove_bandstructure_band_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandstructure',
            name='folder_location',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
