# Generated by Django 2.0.1 on 2018-01-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0015_bandstructure_folder_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandstructure',
            name='band_structure',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
