# Generated by Django 2.0.1 on 2018-01-30 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0017_remove_bandstructure_band_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_method', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='idinfo',
            name='method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.Method'),
        ),
        migrations.AlterField(
            model_name='idinfo',
            name='specific_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.SpecificMethod'),
        ),
    ]
