# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-09 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0018_auto_20180130_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atomicpositions',
            name='Z',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='atomicpositions',
            name='a',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='atomicpositions',
            name='alpha',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='atomicpositions',
            name='b',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='atomicpositions',
            name='beta',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='atomicpositions',
            name='c',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='atomicpositions',
            name='gamma',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='atomicpositions',
            name='volume',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi_isbn',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='system',
            name='compound_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='system',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='system',
            name='formula',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='system',
            name='group',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='system',
            name='inorganic',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='system',
            name='organic',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=100),
        ),
    ]
