# Generated by Django 2.0.1 on 2018-01-31 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0018_auto_20180130_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idinfo',
            name='method',
        ),
        migrations.RemoveField(
            model_name='idinfo',
            name='specific_method',
        ),
    ]
