# Generated by Django 2.0.1 on 2018-03-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0019_auto_20180209_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='excitonemission',
            name='plotted',
            field=models.BooleanField(default=False),
        ),
    ]
