# Generated by Django 2.0.1 on 2018-01-31 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0019_auto_20180131_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='idinfo',
            name='method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.Method'),
        ),
        migrations.AddField(
            model_name='idinfo',
            name='specific_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.SpecificMethod'),
        ),
    ]
