# Generated by Django 2.0.1 on 2018-03-18 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0019_auto_20180209_1534'),
        ('materials', '0020_auto_20180131_0232'),
    ]

    operations = [
    ]
