# Generated by Django 2.0.1 on 2018-03-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0021_atomicpositions_plotted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atomicpositions',
            name='plotted',
        ),
        migrations.AddField(
            model_name='bandstructure',
            name='plotted',
            field=models.BooleanField(default=False),
        ),
    ]
