# Generated by Django 2.0.1 on 2018-03-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0022_auto_20180320_1820'),
        ('materials', '0021_merge_20180318_2207'),
    ]

    operations = [
    ]
