# Generated by Django 2.0.1 on 2018-03-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0023_merge_20180320_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='idinfo',
            name='data_extraction_method',
            field=models.CharField(default='TBD', max_length=500),
        ),
        migrations.AddField(
            model_name='idinfo',
            name='source',
            field=models.CharField(default='TBD', max_length=500),
        ),
    ]
