# Generated by Django 2.0.1 on 2018-03-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0024_auto_20180321_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idinfo',
            name='data_extraction_method',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='idinfo',
            name='source',
            field=models.CharField(max_length=500),
        ),
    ]
