# Generated by Django 2.0.1 on 2018-03-24 00:11

from django.db import migrations, models
import django.db.models.deletion
import materials.models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0025_auto_20180321_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='SynthesisMethod',
            fields=[
                ('idinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='materials.IDInfo')),
                ('synthesis_method', models.TextField()),
                ('syn_file', models.FileField(blank=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.System')),
            ],
            bases=('materials.idinfo',),
        ),
        migrations.RemoveField(
            model_name='bandgap',
            name='idinfo_ptr',
        ),
        migrations.RemoveField(
            model_name='bandgap',
            name='system',
        ),
        migrations.DeleteModel(
            name='BandGap',
        ),
    ]
