# Generated by Django 2.0.1 on 2018-03-24 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0026_auto_20180324_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synthesismethod',
            name='syn_file',
        ),
    ]
