# Generated by Django 2.0.1 on 2018-03-24 00:13

from django.db import migrations, models
import materials.models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0027_remove_synthesismethod_syn_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='synthesismethod',
            name='syn_file',
            field=models.FileField(blank=True),
        ),
    ]
