# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-05 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0028_synthesismethod_syn_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandstructure',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
