# Generated by Django 2.0.1 on 2018-06-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0029_bandstructure_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandstructure',
            name='band_gap',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='synthesismethod',
            name='product',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='synthesismethod',
            name='remarks',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='synthesismethod',
            name='starting_materials',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='synthesismethod',
            name='synthesis_method',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
