# Generated by Django 2.0.1 on 2018-07-23 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0032_auto_20180703_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='atomicpositions',
            name='synthesis_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.SynthesisMethod'),
        ),
    ]
