# Generated by Django 2.0.1 on 2018-07-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0033_atomicpositions_synthesis_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='idinfo',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
    ]
