# Generated by Django 2.0.1 on 2018-07-26 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0034_auto_20180724_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandstructure',
            name='synthesis_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.SynthesisMethod'),
        ),
        migrations.AddField(
            model_name='excitonemission',
            name='synthesis_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.SynthesisMethod'),
        ),
    ]
