# Generated by Django 2.0.1 on 2019-01-18 17:28

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('materials', '0036_auto_20180726_2048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='PropertyOld',
        ),
    ]
