# Generated by Django 2.0.1 on 2019-01-23 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0038_property_unit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
