# Generated by Django 2.0.1 on 2019-01-23 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0039_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datapoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_datapoint_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dataseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_dataseries_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=1000)),
                ('visible', models.BooleanField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_dataset_created_by', to=settings.AUTH_USER_MODEL)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.Publication')),
                ('set_property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.Property')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.System')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_dataset_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NumericalValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField()),
                ('value_type', models.PositiveSmallIntegerField(choices=[(0, 'accurate'), (1, 'approximate'), (2, 'lower_bound'), (3, 'upper_bound'), (4, 'error')])),
                ('qualifier', models.PositiveSmallIntegerField(choices=[(0, 'primary'), (1, 'secondary')])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_numericalvalue_created_by', to=settings.AUTH_USER_MODEL)),
                ('datapoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Datapoint')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.Unit')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_numericalvalue_updated_by', to=settings.AUTH_USER_MODEL)),
                ('value_property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.Property')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NumericalValueFixed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField()),
                ('value_type', models.PositiveSmallIntegerField(choices=[(0, 'accurate'), (1, 'approximate'), (2, 'lower_bound'), (3, 'upper_bound'), (4, 'error')])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_numericalvaluefixed_created_by', to=settings.AUTH_USER_MODEL)),
                ('dataseries', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.Dataseries')),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.Dataset')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.Unit')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_numericalvaluefixed_updated_by', to=settings.AUTH_USER_MODEL)),
                ('value_property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.Property')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dataseries',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Dataset'),
        ),
        migrations.AddField(
            model_name='dataseries',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_dataseries_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='dataseries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Dataseries'),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_datapoint_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
