# Generated by Django 2.0.1 on 2019-02-16 22:26

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('accounts', '0003_auto_20180123_0354'),
        ('materials', '0041_dataset_plotted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SynthesisMethod',
            new_name='SynthesisMethodOld',
        ),
    ]
