# Generated by Django 2.0.1 on 2019-02-16 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0042_auto_20190216_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputationalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('nonperturbative_level', models.CharField(max_length=50)),
                ('kgrid', models.CharField(max_length=40)),
                ('relativity_level', models.CharField(max_length=40)),
                ('SO_coupling', models.BooleanField()),
                ('basis', models.CharField(max_length=100)),
                ('postprocessing', models.CharField(max_length=100)),
                ('dispersion_correction', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_computationaldetails_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='dataset',
            name='label',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='plotted',
            field=models.BooleanField(),
        ),
        migrations.AddField(
            model_name='computationaldetails',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Dataset'),
        ),
        migrations.AddField(
            model_name='computationaldetails',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_computationaldetails_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
