# Generated by Django 2.1.7 on 2019-02-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0044_auto_20190216_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='set_property',
            new_name='primary_property',
        ),
        migrations.AlterField(
            model_name='dataseries',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
