# Generated by Django 2.1.7 on 2019-02-20 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0045_auto_20190220_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numericalvaluefixed',
            old_name='value_property',
            new_name='physical_property',
        ),
        migrations.RemoveField(
            model_name='numericalvalue',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='numericalvalue',
            name='value_property',
        ),
        migrations.AddField(
            model_name='dataset',
            name='primary_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_unit', to='materials.Unit'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='secondary_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_property', to='materials.Property'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='secondary_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_unit', to='materials.Unit'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='primary_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_property', to='materials.Property'),
        ),
    ]
