# Generated by Django 2.1.7 on 2019-02-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0046_auto_20190220_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='crystal_system',
            field=models.PositiveSmallIntegerField(choices=[(0, 'triclinic'), (1, 'monoclinic'), (2, 'orthorhombic'), (3, 'tetragonal'), (4, 'trigonal'), (5, 'hexagonal'), (6, 'cubic')], default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='sample_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'single crystal'), (1, 'powder'), (2, 'film')], default=0),
            preserve_default=False,
        ),
    ]
