# Generated by Django 2.1.7 on 2019-02-20 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0048_remove_dataset_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExperimentalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_experimentaldetails_created_by', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Dataset')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_experimentaldetails_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SynthesisMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('starting_materials', models.TextField(blank=True, max_length=1000)),
                ('product', models.TextField(blank=True, max_length=1000)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_synthesismethod_created_by', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Dataset')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_synthesismethod_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='computationaldetails',
            old_name='nonperturbative_level',
            new_name='level_of_theory',
        ),
        migrations.RemoveField(
            model_name='computationaldetails',
            name='SO_coupling',
        ),
        migrations.RemoveField(
            model_name='computationaldetails',
            name='dispersion_correction',
        ),
        migrations.RemoveField(
            model_name='computationaldetails',
            name='postprocessing',
        ),
        migrations.AddField(
            model_name='computationaldetails',
            name='numerical_accuracy',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computationaldetails',
            name='xc_functional',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='computational_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.ComputationalDetails'),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_comment_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='experimental_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.ExperimentalDetails'),
        ),
        migrations.AddField(
            model_name='comment',
            name='synthesis_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.SynthesisMethod'),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_comment_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
