# Generated by Django 2.1.7 on 2019-03-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0049_auto_20190220_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='require_input_files',
            field=models.BooleanField(default=False),
        ),
    ]
