# Generated by Django 2.1.7 on 2019-03-18 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0053_dataset_representative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialproperty',
            name='idinfo_ptr',
        ),
        migrations.RemoveField(
            model_name='materialproperty',
            name='property',
        ),
        migrations.RemoveField(
            model_name='materialproperty',
            name='system',
        ),
        migrations.DeleteModel(
            name='MaterialProperty',
        ),
        migrations.DeleteModel(
            name='PropertyOld',
        ),
    ]
