# Generated by Django 2.1.7 on 2019-03-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0054_auto_20190318_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='dimensionality',
            field=models.PositiveSmallIntegerField(choices=[(3, 3), (2, 2)]),
        ),
    ]
