# Generated by Django 2.1.7 on 2019-03-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0055_auto_20190327_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapointsymbol',
            name='counter',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='numericalvalue',
            name='counter',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='numericalvalue',
            name='qualifier',
            field=models.PositiveSmallIntegerField(choices=[(0, 'primary'), (1, 'secondary')], default=0),
        ),
        migrations.AlterField(
            model_name='numericalvalue',
            name='value_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'accurate'), (1, 'approximate'), (2, 'lower_bound'), (3, 'upper_bound'), (4, 'error')], default=0),
        ),
        migrations.AlterField(
            model_name='numericalvaluefixed',
            name='value_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'accurate'), (1, 'approximate'), (2, 'lower_bound'), (3, 'upper_bound'), (4, 'error')], default=0),
        ),
    ]
