# Generated by Django 2.1.7 on 2019-03-29 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0056_auto_20190328_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='crystal_system',
            field=models.PositiveSmallIntegerField(choices=[(0, 'triclinic'), (1, 'monoclinic'), (2, 'orthorhombic'), (3, 'tetragonal'), (4, 'trigonal'), (5, 'hexagonal'), (6, 'cubic'), (7, 'unknown')]),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.Publication'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='sample_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'single crystal'), (1, 'powder'), (2, 'film'), (3, 'unknown')]),
        ),
    ]
