# Generated by Django 2.1.7 on 2019-04-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0058_auto_20190329_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numericalvalue',
            name='value_type',
            field=models.PositiveSmallIntegerField(choices=[(0, ''), (1, '≈'), (2, '>'), (3, '<'), (4, 'error')], default=0),
        ),
        migrations.AlterField(
            model_name='numericalvaluefixed',
            name='value_type',
            field=models.PositiveSmallIntegerField(choices=[(0, ''), (1, '≈'), (2, '>'), (3, '<'), (4, 'error')], default=0),
        ),
    ]
