# Generated by Django 2.1.7 on 2019-04-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0059_auto_20190331_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='numericalvaluefixed',
            name='counter',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
