# Generated by Django 2.1.7 on 2019-04-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0060_numericalvaluefixed_counter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publication',
            new_name='Reference',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='publication',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='idinfo',
            old_name='publication',
            new_name='reference',
        ),
    ]
