# Generated by Django 2.1.7 on 2019-04-04 16:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('materials', '0060_numericalvaluefixed_counter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publication',
            new_name='Reference',
        ),
        migrations.RemoveField(
            model_name='author',
            name='publication',
        ),
        migrations.AddField(
            model_name='author',
            name='reference',
            field=models.ManyToManyField(to='materials.Reference'),
        ),
        migrations.RenameField(
            model_name='idinfo',
            old_name='publication',
            new_name='reference',
        ),
    ]
