# Generated by Django 2.1.7 on 2019-04-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0061_auto_20190404_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='institution',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
