# Generated by Django 2.1.7 on 2019-04-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0062_auto_20190405_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='group',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
