# Generated by Django 2.1.7 on 2019-04-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0064_auto_20190411_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numericalvalue',
            name='value_type',
            field=models.PositiveSmallIntegerField(choices=[(0, ''), (1, '≈'), (2, '>'), (3, '<')], default=0),
        ),
        migrations.AlterField(
            model_name='numericalvaluefixed',
            name='value_type',
            field=models.PositiveSmallIntegerField(choices=[(0, ''), (1, '≈'), (2, '>'), (3, '<')], default=0),
        ),
    ]
