# Generated by Django 2.1.7 on 2019-04-11 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0065_auto_20190411_1510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatapointSymbol',
            new_name='Symbol',
        ),
        migrations.RenameField(
            model_name='symbol',
            old_name='symbol',
            new_name='value',
        ),

        migrations.AlterField(
            model_name='symbol',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_symbol_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_symbol_updated_by', to=settings.AUTH_USER_MODEL),
        ),

    ]
