# Generated by Django 2.1.7 on 2019-04-16 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0067_datasetfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='error',
            name='id',
        ),
        migrations.AlterField(
            model_name='error',
            name='numerical_value',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='materials.NumericalValue'),
        ),
    ]
