# Generated by Django 2.1.7 on 2019-04-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0068_auto_20190415_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='experimental',
            new_name='is_experimental',
        ),
    ]
