# Generated by Django 2.1.7 on 2019-04-16 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0069_auto_20190416_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='computational_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.ComputationalDetails'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='experimental_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.ExperimentalDetails'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='synthesis_method',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.SynthesisMethod'),
        ),
        migrations.AlterField(
            model_name='computationaldetails',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computational', to='materials.Dataset'),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='dataseries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datapoints', to='materials.Dataseries'),
        ),
        migrations.AlterField(
            model_name='experimentaldetails',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimental', to='materials.Dataset'),
        ),
        migrations.AlterField(
            model_name='numericalvalue',
            name='datapoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='materials.Datapoint'),
        ),
        migrations.AlterField(
            model_name='numericalvaluefixed',
            name='dataseries',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_values', to='materials.Dataseries'),
        ),
        migrations.AlterField(
            model_name='numericalvaluefixed',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_values', to='materials.Dataset'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='datapoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='materials.Datapoint'),
        ),
        migrations.AlterField(
            model_name='synthesismethod',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synthesis', to='materials.Dataset'),
        ),
    ]
