# Generated by Django 2.1.7 on 2019-04-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0070_auto_20190416_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='computationaldetails',
            name='basis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='computationaldetails',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='computationaldetails',
            name='kgrid',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='computationaldetails',
            name='level_of_theory',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='computationaldetails',
            name='numerical_accuracy',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='computationaldetails',
            name='relativity_level',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='computationaldetails',
            name='xc_functional',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dataseries',
            name='label',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataset',
            name='extraction_method',
            field=models.CharField(blank=True, default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experimentaldetails',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experimentaldetails',
            name='method',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='synthesismethod',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='synthesismethod',
            name='product',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='synthesismethod',
            name='starting_materials',
            field=models.TextField(blank=True),
        ),
    ]
