# Generated by Django 2.1.7 on 2019-04-22 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0071_auto_20190416_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atomicpositions',
            name='idinfo_ptr',
        ),
        migrations.RemoveField(
            model_name='atomicpositions',
            name='synthesis_method',
        ),
        migrations.RemoveField(
            model_name='atomicpositions',
            name='system',
        ),
        migrations.DeleteModel(
            name='AtomicPositions',
        ),
    ]
