# Generated by Django 2.1.7 on 2019-04-29 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0075_auto_20190428_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computationaldetails',
            options={'verbose_name_plural': 'computational details'},
        ),
        migrations.AlterModelOptions(
            name='dataseries',
            options={'verbose_name_plural': 'dataseries'},
        ),
        migrations.AlterModelOptions(
            name='experimentaldetails',
            options={'verbose_name_plural': 'experimental details'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'properties'},
        ),
        migrations.AlterField(
            model_name='computationaldetails',
            name='basis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='computationaldetails',
            name='code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='computationaldetails',
            name='kgrid',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='computationaldetails',
            name='level_of_theory',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='computationaldetails',
            name='numerical_accuracy',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='computationaldetails',
            name='relativity_level',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='computationaldetails',
            name='xc_functional',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='label',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='secondary_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_property', to='materials.Property'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='secondary_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_unit', to='materials.Unit'),
        ),
    ]
