# Generated by Django 2.1.7 on 2019-04-30 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0076_auto_20190429_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='primary_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_unit', to='materials.Unit'),
        ),
    ]
