# Generated by Django 2.2.1 on 2019-05-20 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0081_rename_dataseries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'verbose_name_plural': 'data sets'},
        ),
        migrations.AlterModelOptions(
            name='subset',
            options={'verbose_name_plural': 'data subsets'},
        ),
        migrations.RenameField(
            model_name='datapoint',
            old_name='dataseries',
            new_name='subset',
        ),
        migrations.RenameField(
            model_name='numericalvaluefixed',
            old_name='dataseries',
            new_name='subset',
        ),
        migrations.AlterField(
            model_name='subset',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_subset_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subset',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsets', to='materials.Dataset'),
        ),
        migrations.AlterField(
            model_name='subset',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_subset_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
