# Generated by Django 2.2.1 on 2019-05-23 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0084_auto_20190522_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computationaldetails',
            old_name='basis',
            new_name='basis_set_definition',
        ),
        migrations.RenameField(
            model_name='computationaldetails',
            old_name='kgrid',
            new_name='k_point_grid',
        ),
        migrations.RenameField(
            model_name='computationaldetails',
            old_name='relativity_level',
            new_name='level_of_relativity',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='linked_to',
            field=models.ManyToManyField(blank=True, related_name='_dataset_linked_to_+', to='materials.Dataset'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.Reference'),
        ),
    ]
