# Generated by Django 2.2.1 on 2019-06-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0088_auto_20190531_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='subset',
            name='crystal_system',
            field=models.PositiveSmallIntegerField(choices=[(0, 'triclinic'), (1, 'monoclinic'), (2, 'orthorhombic'), (3, 'tetragonal'), (4, 'trigonal'), (5, 'hexagonal'), (6, 'cubic'), (7, 'unknown')], default=1),
            preserve_default=False,
        ),
    ]
