# Generated by Django 2.2.1 on 2019-06-06 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0090_remove_dataset_crystal_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numericalvaluefixed',
            name='subset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_values', to='materials.Subset'),
            preserve_default=False,
        ),
    ]
