# Generated by Django 2.2.1 on 2019-06-06 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0091_auto_20190606_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseTransition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.FloatField()),
                ('value_type', models.PositiveSmallIntegerField(choices=[(0, ''), (1, '≈'), (2, '>'), (3, '<')], default=0)),
                ('counter', models.PositiveSmallIntegerField(default=0)),
                ('crystal_system_final', models.PositiveSmallIntegerField(choices=[(0, 'triclinic'), (1, 'monoclinic'), (2, 'orthorhombic'), (3, 'tetragonal'), (4, 'trigonal'), (5, 'hexagonal'), (6, 'cubic'), (7, 'unknown')])),
                ('space_group_initial', models.CharField(blank=True, max_length=50)),
                ('space_group_final', models.CharField(blank=True, max_length=50)),
                ('direction', models.CharField(blank=True, max_length=50)),
                ('hysteresis', models.CharField(blank=True, max_length=50)),
                ('error', models.FloatField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_phasetransition_created_by', to=settings.AUTH_USER_MODEL)),
                ('subset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_transitions', to='materials.Subset')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_phasetransition_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
