# Generated by Django 2.2.1 on 2019-06-19 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0092_phasetransition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='label',
            new_name='caption',
        ),
    ]
