# Generated by Django 2.2.1 on 2019-07-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0093_auto_20190619_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='reference',
        ),
        migrations.AddField(
            model_name='author',
            name='references',
            field=models.ManyToManyField(related_name='authors', to='materials.Reference'),
        ),
        migrations.RemoveField(
            model_name='reference',
            name='author_count',
        ),
    ]
