# Generated by Django 2.2.1 on 2019-08-21 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0098_auto_20190820_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subset',
            options={'verbose_name_plural': 'data subsets (read-only)'},
        ),
    ]
