# Generated by Django 2.2.1 on 2019-09-03 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0099_auto_20190821_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='materials.Reference'),
        ),
    ]
