# Generated by Django 2.2.1 on 2019-09-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0100_auto_20190903_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='inorganic',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='system',
            name='organic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
