# Generated by Django 3.1.8 on 2021-05-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0103_dataset_space_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='group',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
