# Generated by Django 3.1.8 on 2021-06-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0104_auto_20210525_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='iupac',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='system',
            name='group',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
