# Generated by Django 3.1.12 on 2022-03-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0106_system_derived_to_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='derived_to_from',
            field=models.ManyToManyField(blank=True, to='materials.System'),
        ),
    ]
