# Generated by Django 3.1.12 on 2022-03-31 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0108_auto_20220310_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='materials.system'),
        ),
    ]
