# Generated by Django 3.1.12 on 2022-03-31 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0109_auto_20220331_0922'),
        ('materials', '0107_auto_20220308_1328'),
    ]

    operations = [
    ]
