# Generated by Django 3.1.14 on 2022-04-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0110_merge_20220331_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='derived_to_from',
            field=models.ManyToManyField(blank=True, related_name='_system_derived_to_from_+', to='materials.System'),
        ),
    ]
