# Generated by Django 3.1.14 on 2022-04-28 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0112_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dataset', to='materials.system'),
        ),
    ]
