# Generated by Django 3.1.14 on 2022-05-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0113_auto_20220428_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='dimensionality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='system',
            name='n',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
