# Generated by Django 3.1.14 on 2022-07-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0115_auto_20220601_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='dimensionality',
            field=models.PositiveSmallIntegerField(choices=[(4, 3), (3, 2.5), (2, 2), (1, 1), (0, 0)]),
        ),
    ]
