# Generated by Django 3.1.14 on 2022-07-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0116_auto_20220707_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='dimensionality',
            field=models.PositiveSmallIntegerField(choices=[(4, 3), (3, 2.5), (2, 2), (1, 1), (0, 0)], default=0),
        ),
    ]
