# Generated by Django 3.1.14 on 2022-07-12 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0117_auto_20220707_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='subset',
            name='space_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.spacegroup'),
        ),
    ]
