# Generated by Django 3.1.14 on 2022-07-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0118_subset_space_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subset',
            name='space_group',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
