# Generated by Django 3.1.14 on 2022-07-15 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0119_auto_20220712_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='subset',
            name='space_group_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.spacegroup'),
        ),
    ]
