# Generated by Django 3.1.14 on 2022-08-11 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0121_auto_20220715_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentaldetails',
            name='system',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experimental', to='materials.system'),
        ),
        migrations.AddField(
            model_name='synthesismethod',
            name='system',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='synthesis', to='materials.system'),
        ),
    ]
