# Generated by Django 4.1 on 2022-09-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0123_alter_additionalfile_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='message',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
