# Generated by Django 4.1 on 2022-09-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0124_system_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='message',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
