# Generated by Django 4.1 on 2022-11-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0126_dataset_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='method',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
