# Generated by Django 3.1.14 on 2024-04-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0127_property_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='linked_to',
            field=models.ManyToManyField(blank=True, related_name='_dataset_linked_to_+', to='materials.Dataset'),
        ),
        migrations.AlterField(
            model_name='system',
            name='derived_to_from',
            field=models.ManyToManyField(blank=True, related_name='_system_derived_to_from_+', to='materials.System'),
        ),
    ]
