# Generated by Django 3.1.14 on 2024-09-30 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0127_property_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='linked_to',
            field=models.ManyToManyField(blank=True, related_name='_dataset_linked_to_+', to='materials.Dataset'),
        ),
        migrations.AlterField(
            model_name='system',
            name='derived_to_from',
            field=models.ManyToManyField(blank=True, related_name='_system_derived_to_from_+', to='materials.System'),
        ),
        migrations.CreateModel(
            name='System_Stoichiometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stoichiometry', models.CharField(default='N/A', help_text='Please provide the stoichiometry value in the format: C:6,H:12,O:1', max_length=255)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.system')),
            ],
        ),
        migrations.CreateModel(
            name='Stoichiometry_Elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=1000)),
                ('string_value', models.CharField(default='0', max_length=1000)),
                ('float_value', models.FloatField(default=0.0)),
                ('system_stoichiometry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.system_stoichiometry')),
            ],
        ),
    ]
