# Generated by Django 3.1.14 on 2024-09-30 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0128_auto_20240930_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoichiometry_elements',
            name='system_stoichiometry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.system_stoichiometry'),
        ),
    ]
