# Generated by Django 3.1.14 on 2024-09-30 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0129_auto_20240930_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_stoichiometry',
            name='system',
        ),
        migrations.DeleteModel(
            name='Stoichiometry_Elements',
        ),
        migrations.DeleteModel(
            name='System_Stoichiometry',
        ),
    ]
