from django.urls import path
from django.urls import re_path
from materials import views


app_name = 'materials'
urlpatterns = [
    path('', views.SearchFormView.as_view(), name='materials_home'),
    path('<int:pk>', views.SystemDetailView.as_view(),
         name='materials_system'),
    re_path(r'^(?P<pk>\d+)_(?P<pk_aa>\d+)_(?P<pk_syn>\d+)_(?P<pk_ee>\d+)_'
            r'(?P<pk_bs>\d+)$', views.SpecificSystemView.as_view(),
            name='specific_materials_system'),
    path('<int:sys>/update-atomic-positions/<int:pk>',
         views.AtomicPositionsUpdateView.as_view(), name='update_a_pos'),
    path('<int:sys>/delete-atomic-positions/<int:pk>',
         views.AtomicPositionsDeleteView.as_view(), name='delete_a_pos'),
    path('<int:sys>/update-synthesis/<int:pk>',
         views.SynthesisMethodUpdateView.as_view(), name='update_synthesis'),
    path('<int:sys>/delete-synthesis/<int:pk>',
         views.SynthesisMethodDeleteView.as_view(), name='delete_synthesis'),
    path('<int:sys>/update-exciton-emission/<int:pk>',
         views.ExcitonEmissionUpdateView.as_view(),
         name='update_exciton_emission'),
    path('<int:sys>/delete-exciton-emission/<int:pk>',
         views.ExcitonEmissionDeleteView.as_view(),
         name='delete_exciton_emission'),
    path('<int:sys>/update-band-structure/<int:pk>',
         views.BandStructureUpdateView.as_view(),
         name='update_band_structure'),
    path('<int:sys>/delete-band-structure/<int:pk>',
         views.BandStructureDeleteView.as_view(),
         name='delete_band_structure'),
    path('<int:sys>/update-property/<int:pk>',
         views.PropertyUpdateView.as_view(), name='update_property'),
    re_path(r'^(?P<sys>\d+)/delete-property/(?P<pk>\d+)',
            views.PropertyDeleteView.as_view(), name='delete_property'),
    path('<int:system_pk>/publish-system/<int:dataset_pk>',
         views.toggle_dataset_visibility, name='publish_system'),
    path('<int:system_pk>/toggle-plotted/<int:dataset_pk>',
         views.toggle_dataset_plotted, name='toggle_plotted'),
    path('download-dataset-files/<int:pk>', views.download_dataset_files,
         name='download_dataset_files'),
    path('download-input-data-file/<int:pk>', views.download_input_file,
         name='download_input_file'),
    path('<int:system_pk>/delete-dataset/<int:dataset_pk>',
         views.delete_dataset_and_files, name='delete_dataset'),
    path('<int:pk>/all-a-pos', views.all_a_pos, name='all_a_pos'),
    re_path(r'^(?P<pk>\d+)/(?P<data_type>.*)$', views.all_entries,
            name='all_entries'),
    path('add-pub', views.AddPubView.as_view(), name='add_publication'),
    path('search-pub', views.SearchPubView.as_view(),
         name='search_publication'),
    path('search-system', views.SearchSystemView.as_view(),
         name='search_system'),
    path('add-system', views.AddSystemView.as_view(), name='add_system'),
    path('add-author', views.AddAuthorView.as_view(), name='add_author'),
    path('search-author', views.SearchAuthorView.as_view(),
         name='search_author'),
    path('author-count', views.AddAuthorsToPublicationView.as_view(),
         name='author_count'),
    path('add-a-pos', views.AddAPosView.as_view(), name='add_a_pos'),
    path('add-exciton-emission', views.AddExcitonEmissionView.as_view(),
         name='add_exciton_emission'),
    path('add-synthesis', views.AddSynthesisMethodView.as_view(),
         name='add_synthesis'),
    path('add-band-structure', views.AddBandStructureView.as_view(),
         name='add_band_structure'),
    path('add-material-property', views.AddMaterialPropertyView.as_view(),
         name='add_material_property'),
    path('add-data', views.AddDataView.as_view(), name='add_data'),
    path('add-property', views.add_property, name='add_property'),
    path('add-unit', views.add_unit, name='add_unit'),
    path('submit-data', views.submit_data, name='submit_data'),
    path('add-tag', views.AddTagView.as_view(), name='add_tag'),
    re_path(r'^data-dl/(?P<data_type>.*)/(?P<pk>\d+)$', views.data_dl,
            name='data_dl'),
    path('update-system/<int:pk>', views.SystemUpdateView.as_view(),
         name='update_system'),
    path('publication-data/<int:pk>', views.publication_data,
         name='publication_data'),
    path('dataset-<int:pk>/image.png', views.dataset_image,
         name='dataset_image'),
    path('dataset-<int:pk>/data.txt', views.dataset_data, name='dataset_data'),
    path('publication/<int:pk>', views.PublicationDetailView.as_view(),
         name='publication'),
    path('autofill-input-data', views.autofill_input_data,
         name='autofill_input_data'),
]
