# -*- coding: utf-8 -*-
from django.conf.urls import re_path
from .views import (
    SearchFormView, SystemView, SpecificSystemView, AtomicPositionsUpdateView,
    AtomicPositionsDeleteView, SynthesisMethodUpdateView,
    SynthesisMethodDeleteView, ExcitonEmissionUpdateView,
    ExcitonEmissionDeleteView, BandStructureUpdateView,
    BandStructureDeleteView, PropertyUpdateView, PropertyDeleteView, all_a_pos,
    all_entries, AddPubView, SearchPubView, SearchSystemView, AddSystemView,
    AddAuthorView, SearchAuthorView, AddAuthorsToPublicationView, AddAPosView,
    AddExcitonEmissionView, AddSynthesisMethodView, AddBandStructureView,
    AddMaterialPropertyView, AddDataView, AddTagView, data_dl,
    SystemUpdateView, toggle_bandstructure_visibility,
    )


app_name = "materials"

urlpatterns = [
    re_path(r'^$', SearchFormView.as_view(), name='materials_home'),
    re_path(r'^(?P<pk>\d+)$', SystemView.as_view(), name='materials_system'),
    re_path(r'^(?P<pk>\d+)_(?P<pk_aa>\d+)_(?P<pk_syn>\d+)_(?P<pk_ee>\d+)_'
            r'(?P<pk_bs>\d+)$', SpecificSystemView.as_view(),
            name='specific_materials_system'),
    re_path(r'^(?P<sys>\d+)/update-atomic-positions/(?P<pk>\d+)$',
            AtomicPositionsUpdateView.as_view(), name='update_a_pos'),
    re_path(r'^(?P<sys>\d+)/delete-atomic-positions/(?P<pk>\d+)$',
            AtomicPositionsDeleteView.as_view(), name='delete_a_pos'),
    re_path(r'^(?P<sys>\d+)/update-synthesis/(?P<pk>\d+)$',
            SynthesisMethodUpdateView.as_view(), name='update_synthesis'),
    re_path(r'^(?P<sys>\d+)/delete-synthesis/(?P<pk>\d+)$',
            SynthesisMethodDeleteView.as_view(), name='delete_synthesis'),
    re_path(r'^(?P<sys>\d+)/update-exciton-emission/(?P<pk>\d+)$',
            ExcitonEmissionUpdateView.as_view(),
            name='update_exciton_emission'),
    re_path(r'^(?P<sys>\d+)/delete-exciton-emission/(?P<pk>\d+)$',
            ExcitonEmissionDeleteView.as_view(),
            name='delete_exciton_emission'),
    re_path(r'^(?P<sys>\d+)/update-band-structure/(?P<pk>\d+)$',
            BandStructureUpdateView.as_view(), name='update_band_structure'),
    re_path(r'^(?P<sys>\d+)/delete-band-structure/(?P<pk>\d+)$',
            BandStructureDeleteView.as_view(), name='delete_band_structure'),
    re_path(r'^(?P<sys>\d+)/update-property/(?P<pk>\d+)$',
            PropertyUpdateView.as_view(), name='update_property'),
    re_path(r'^(?P<sys>\d+)/delete-property/(?P<pk>\d+)$',
            PropertyDeleteView.as_view(), name='delete_property'),
    re_path(r'^(?P<id>\d+)/all-a-pos$', all_a_pos, name='all_a_pos'),
    re_path(r'^(?P<sys>\d+)/toggle-bandstructure-visibility/(?P<pk>\d+)$',
            toggle_bandstructure_visibility,
            name='toggle_bandstructure_visibility'),
    re_path(r'^(?P<id>\d+)/(?P<type>.*)$', all_entries, name='all_entries'),
    re_path(r'^add-pub$', AddPubView.as_view(), name='add_publication'),
    re_path(r'^search-pub$', SearchPubView.as_view(),
            name='search_publication'),
    re_path(r'^search-system$', SearchSystemView.as_view(),
            name='search_system'),
    re_path(r'^add-system$', AddSystemView.as_view(), name='add_system'),
    re_path(r'^add-author$', AddAuthorView.as_view(), name='add_author'),
    re_path(r'^search-author$', SearchAuthorView.as_view(),
            name='search_author'),
    re_path(r'^author-count$', AddAuthorsToPublicationView.as_view(),
            name='author_count'),
    re_path(r'^add-a-pos$', AddAPosView.as_view(), name='add_a_pos'),
    re_path(r'^add-exciton-emission$', AddExcitonEmissionView.as_view(),
            name='add_exciton_emission'),
    re_path(r'^add-synthesis$', AddSynthesisMethodView.as_view(),
            name='add_synthesis'),
    re_path(r'^add-band-structure$', AddBandStructureView.as_view(),
            name='add_band_structure'),
    re_path(r'^add-material-property$', AddMaterialPropertyView.as_view(),
            name='add_material_property'),
    re_path(r'^add-data$', AddDataView.as_view(), name='add_data'),
    re_path(r'^add-tag$', AddTagView.as_view(), name='add_tag'),
    re_path(r'^data-dl/(?P<type>.*)/(?P<id>\d+)$', data_dl, name='data_dl'),
    re_path(r'^update-system/(?P<pk>\d+)$', SystemUpdateView.as_view(),
            name='update_system'),
]
